### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94

### ISSUE THREAD

**Issue by yucongo** [tvst/jsbuilder#2]
Hi. Thanks for the nice package.

`with open("README.md", "r") as fh:
    long_description = fh.read()`

This line in `setup.py` is causing some problem when doing `pip install  jsbuilder`  in certain systems (non-utf8 Windows for example): 

```bash
File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-mtlho8cf\jsbuilder_c32551d6c9a34bb488d8b58fca88b832\setup.py", line 4, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 14: illegal multibyte sequence
```

A small patch may fix the problem: 
```python
with open("README.md", "r", encoding='utf8') as fh:
```

**Comment by tvst** [comment]
Merged, thanks!
